### PR TITLE
Fix for not being able to put some cars on

### PR DESCRIPTION
**Pull request by PERPGamer**
This fixes the issue with emergency vehicles on the trailer

### CODE REVIEW

**Comment by TanguyOrtegat** [comment]
that is not the correct way to look for a vehicle, it will work, but if you do look not the correct side, it will attach the wrong vehicle, of even it will try to attach the trailer to the trailer

**Comment by TanguyOrtegat** [comment]
you don't have the closest vehicle, but the vehicle you are looking at

**Comment by TanguyOrtegat** [comment]
look here. we discussed about the issue. I did give a temporary fix/sollution :)
https://forum.fivem.net/t/release-esx-jb-trailer/237508/89?u=jager_bom

**Comment by PERPGamer** [comment]
Alright :) I'll close this then

**Pull request closed without merging**
