### PR TITLE
Add an English language option instead of _only_ French

### PR DESCRIPTION
**Pull request by lze3**

### CODE REVIEW

**Comment by TanguyOrtegat** [comment]
thanks for your work ! but it's not done the correct way, use locales like every esx ressource if you want to do some translations. something like : _U('detatch_vehicle_trailer')
and in locale folder you put the translations :)

**Comment by lze3** [comment]
Ok, that's kinda stupid but okay. I'll update the PR tomorrow.

**Comment by TanguyOrtegat** [comment]
not stupid because if else is not optimised better working with locals easy to configure and easy to add some other languages :)

**Comment by lze3** [comment]
>I'll update the PR tomorrow.

>Closes PR.

Ok then...

**Pull request closed without merging**
